"""oauth user fields

Revision ID: fc166700d5fa
Revises: 3414ea1f885e
Create Date: 2026-07-03 00:08:38.517836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc166700d5fa'
down_revision: Union[str, Sequence[str], None] = '3414ea1f885e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('oauth_subject', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=1024), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint('uq_user_oauth', 'users', ['oauth_provider', 'oauth_subject'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_oauth', 'users', type_='unique')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'oauth_subject')
    op.drop_column('users', 'oauth_provider')
    # ### end Alembic commands ###
