"""folders

Revision ID: ff5779a44f45
Revises: fc166700d5fa
Create Date: 2026-07-04 15:21:02.061762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5779a44f45'
down_revision: Union[str, Sequence[str], None] = 'fc166700d5fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'parent_id', 'name', name='uq_folder_owner_parent_name')
    )
    op.create_index(op.f('ix_folders_owner_id'), 'folders', ['owner_id'], unique=False)
    op.create_index(op.f('ix_folders_parent_id'), 'folders', ['parent_id'], unique=False)
    op.add_column('assets', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_assets_folder_id'), 'assets', ['folder_id'], unique=False)
    op.create_foreign_key(
        'fk_assets_folder_id', 'assets', 'folders', ['folder_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_assets_folder_id', 'assets', type_='foreignkey')
    op.drop_index(op.f('ix_assets_folder_id'), table_name='assets')
    op.drop_column('assets', 'folder_id')
    op.drop_index(op.f('ix_folders_parent_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_owner_id'), table_name='folders')
    op.drop_table('folders')
    # ### end Alembic commands ###
